title: "Philosophy Papers"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
author: 
  name: "David W. Agler"
plugins:
  - jekyll-readme-index # Use README.md as index file