title: "Philosophy Papers"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-readme-index # Use README.md as index file
author: 
  name: "David W. Agler"