title: "Philosophy Papers"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
theme: primer
author: 
  name: "David W. Agler"
plugins:
  - jekyll-readme-index # Use README.md as index file
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock