title: "How to Write Philosophy"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
theme: jekyll-theme-minimal
#url: "https://davidagler.github.io" #base url
relative_url: true
plugins:
  - jekyll-readme-index # Use README.md as index file
author: 
  name: "David W. Agler"