title: "Philosophy Papers"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-readme-index # Use README.md as index file
author: 
  name: "David W. Agler"

social:
  name: David W. Agler
  links:
    - https://x.com/davidagler
    - https://github.com/davidagler
    - https://www.davidagler.com