title: "How to Write Philosophy"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
#theme: jekyll-theme-minimal
#remote_theme: "mmistakes/so-simple-theme@3.2.0"
remote_theme: "riggraz/no-style-please"
relative_url: true
plugins:
  - jekyll-readme-index # Use README.md as index file
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
author: 
  name: "David W. Agler"