title: "How to Write Philosophy"
description: "Basic writing-related instruction for philosophy courses."
markdown: kramdown
theme: minima
plugins:
  - jekyll-readme-index # Use README.md as index file
author: 
  name: "David W. Agler"
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/davidagler" }
    - { platform: twitter, user_url: "https://twitter.com/davidagler" }